### ISSUE TITLE
Testes de parser

### ISSUE THREAD

**Issue by jeandersonbc** [jeandersonbc/plp-tools#3]
É desejado que se tenha testes para os parsers das linguagens implementadas. Xtext tem suporte para isso.

**Comment by leusonmario** [comment]
Implementação inicial dos casos de teste para as linguagens Funcional1 e Imperativa1, a partir dos .JARs gerados pelas linguagens mencionadas.
O número de casos de teste para ambas linguagens será refinado, além da geração de novos testes posteriormente.
